local alpha = require("alpha")
local dashboard = require("alpha.themes.dashboard")

local basil_1 = {
	"                                                                                           ",
	"                                                         -/::..`                           ",
	"                                                        `-ddhdy/:.                         ",
	"                                                        :smmmddddy-`                       ",
	"                                                        /mmNmdhhdmh+`                      ",
	"                                                        -dmmmmmhhddds.                     ",
	"                                                         -hmmdmhhymhdh/                    ",
	"                            `/+/:---.`                    :ddmNNyhhmNNm-                   ",
	"                    ````.---:hdNNdmhs+/-`                 :ymmNmyysyhNNy`                  ",
	"                `:+oyosyyhdmoydmNNNNNNdho-`               :ddmNNmmshymdy.                  ",
	"             `-ohdhoodmdmmmmosdNNNNNNNNNNmy-.             /mmmNNmNdydNhm:                  ",
	"          `/shmddshdmmdmdNmmsyhNNmdNNNNNNNNm+-`           ommNmNmNNNNNNN:                  ",
	"         .odddddyshmmmdmmmmmssdmNNNmhdNNNNNNNNd+`         -ddmmmNNNNNNNN-                  ",
	"      `:shhddhmmmmNNmmmmmmmmd+ymNNNNNNhmMMMMNmdmy-..      `ymNNmmmNmohNN`                  ",
	"     -+hmdmmdhmmNmmmNmmmdhhhdssmNNNNMMNhmMMMNNmhhhss/+.    .hmNNNmmNdshd`                  ",
	"   .ohmdmdmmddmmmmmmdddmhmddydohmNMNMNMNmNNNNNMNmshhdss/-   -dNNNmmmdNoy                   ",
	"  `sdmmmmmmmmdmmmmmhhddNmmmdhdyodmNNNNNNNdNNNNNNNNhddhyoso`  :mNmNNNydhy                   ",
	"  /dddmmdNmNNdmmmmdddmmNmmNmhhh+ymNNNNNNNhmNNNNMMNNhhodyoss:` oNmdmmdydy                   ",
	" :yddmNhymmNmmmdmddmmmmmmmNNmhoyoymNNNNNNNhdNNNNNNMNmsds+o/s+`:mNshdmhdo                   ",
	"`yddmmmymmmmhmmdmsmmmmmmmmNNmhshsoydddmddddhhNNNNNNNNhyoy/:+o+shNhmmmNN:                   ",
	":dddyddhhmdmddmdmdNmmmmmmmmNdydyydyssyhhhhdhhhddyhmNNdsooh+/:oysdmmmNNmo`                  ",
	"`hdydsdssmdmddmmmmmNmmmmmmNmhmdhNmNdyhooyhymdhmmddyhdNsssmhy+++yhNmNNddd-                  ",
	"`hdNmmhohmdmmddmmmmNmmNmmdmNyNmmNNmyydhysoosyydNmdshhhhsydddmymmmmmmNNmdh/                 ",
	"+mmmyhNsdsdmmmdmNmmmmmNNmhydNNNmmNNmmmmddhyooo/dNNhydhhhddmdNdhddddmhdmddho.               ",
	":mmmdoyhNsyhNmmmmmmmmmmNNmmNNNNmmmmNNNNmmdhsosoosymmddmmddmmmmhNdmNd+hyyydNd+              ",
	"`mmmmdhsmshdhhmmmmmmmmNNNNNNNNNNmmNmNNNNhyhysyhyo++syymNmddmd+Nmdmmmmmdooohddy-            ",
	"`yNmmmmmsyysmNmmmmmmmmmNNNNNNNNNNNNmmyhhyhysmmmhhooyss+dmmmmyhNmhmmmmmNmmyymmdds/.         ",
	" /mmdmdmmsdyhyyhhmmmNmmmNNNNNNNNmmmmNyohmdyhmmmmyydhhy/sdmmmhmNNNNmmNNNNNNNNNhhdmmo`       ",
	" /ddmmmmdsmdmmNhdyhdmNmmNNNNNNNNmmmmmmmyhddmmmmmmmdhhhyyomdmmmmmmmmmmNNNNNNmNhyhdhms`      ",
	" +mmmdmmdshmdmNNNdyydyhdNmNNNNmdhdmmmNmhdNNmmmmdmmhshhhdoommmdms//:/sdNMMNNNNNhmNmmd/      ",
	" -mmdddddhsdhhmmmNNNmysmmmddddmmddhdmmmNNNmmmmmmmdhoddddddmmmddh+`-``/mNMMNNNNNhNNmhh.     ",
	" .oyddmsssysysdmmmmhdyhmNmmmddmmmmmmNmmmmmmmmmmmdo+hdddhddmmNmdsh.`  .dmMMMMNNNdNmhhy+:    ",
	" `osdmNmysohohydmmhydmmmNmmmmdddmmmNmNmmmmmmmmmhy++dddmshhdmdmmmdhsooomNMNMMNNNMMNmhhos.   ",
	" `ohmmdmNdhyssyydmdmmmmdddyhdhhdddmdyNNmNmmmmmmhs+shdddoshhdddmmmmmmmNNNdNNNNNNNmmmdmy+:   ",
	"  sdmmmdNNmysssymmdmNmmmmmddyhsysyohdmNNNmmmddmhy/syhddhoyhhhymNNNNNNmNmhsymNMMNNmmhNy//   ",
	" `odmydmmNmy+syshyhydmmmmmmdmmmmyssdmdNNNNmmmdhdyosshhdmdsshhymdNNNNNmmmhsshdmdmNmmdmdy-   ",
	" `.sddoNNmmmdoysohhhyyhdddmmmdmhyyyNhmNNNNNmmmdydyssohddmyyhhdssdmNNNmmNNyy+ddmmmmmmmmh/   ",
	"   -osooNNmNNhhyysyhhhssdddmmsyyhdomhddNNNNNmmmmNmyooysdmyoyhhdmmddmmmmNNNNyhydmmdddddmh-``",
	"    `--+symdmNmhhyyydhdhyyddmhssyyssdhymNNNNNmmmdmyhssssyddymdddmmdmmmmmddydhmNNhhhmdhdm:  ",
	"      `.-oymdhmmdhyyyysyhyydhhddssyysmmyydddhdddmyosyoososhhmmmmmmddddhsyys++sdyddyyhhy/`  ",
	"          /yymddmmdhhhohosyhsoshhos+smdmshmmddddmmmyssssooos+shhhddddhhhyyo//+sdhssyy/`    ",
	"          `//+ohddddhhohhoooosyssyhyshmhhhhmdhdmmNdhhyssyososo/ooosyhddhs+yysyyyhs+:.      ",
	"           `:+osshdmdhdddyyhysssooysoyyysdhmddhymNmdddyyyosososs++oyhhhhhhyhyo+o:`         ",
	"             ./shddmmdddhdyhyhhssys+++ss++syydddddmmmmmmddhhsssssysso+/oyyoo.`             ",
	"               `-oyhdmdssshdhssh+y: ``..`../+yyydddhdmmdddmddyyyyhyhyyhyooso:.             ",
	"                  `.-oyhhydddd+hso``         .:+osyhhddddhdddddssossosy+syosso.            ",
	"                     `.:+shhdh/+:```            -yhhoo+++/+ooss+//-+sosooyysos/`           ",
	"                         `..:/.                  `-+hyooyysssoso+o+/++osyhddy+.`           ",
	"                                                    :oyyhhhhsoshyoyss++osooos.             ",
	"                                                      .:oydhyhyhhh+h+:`                    ",
	"                                                          `./yyyhy--``                     ",
	"                                                                                           ",
}

local basil_2 = {
	"                                                                                                  ",
	"                                                                                                  ",
	"                                                                                                  ",
	"                                                                                                  ",
	"                           ``                                                                     ",
	"                        `-://:-`                                                                  ",
	"                       -//+/++/-                                                                  ",
	"                      .///+++++-                                                                  ",
	"                     ./++++oo+/-                                                                  ",
	"                    .+oo+oooo+//  ..`                                                             ",
	"                    +o+ooooo++//-/ooo+/:                                                          ",
	"                   -+oosooso+//+syyyysso/`                                                        ",
	"                   /oososso+/+oyyyyyyyyyo:                                                        ",
	"                  `+oooooso+ooosyyssyyyhy:                                                        ",
	"                  -+oooooso/s+osyyssyyhhs-                                                        ",
	"                  :+oooooso+o+oyyysyyyhho-                                                        ",
	"                  ++ooosssso++yosyysyhhyo-                                                        ",
	"                 `++oooosssos+oyosysyyhso:                                                        ",
	"                 .++oossssyyo+oyoosyyyyos:                                                        ",
	"                 `+ossyyyyys+oooo+syysoos:            `.-:::///:/::::--.`                         ",
	"                  +ossyyysoo+ooo++oosooos.      `.-/////:://++++//++/++///::-`                    ",
	"                  -oooo+////ooo/+++ooosy/    .-+ooo++++++++++/+++//+++++++++//--`                 ",
	"                  :/+//////:oo//ooooosyy:..-/oossoo++oo+++///://///++++++oo++////:`               ",
	"                `-/::/++++o//oo+oosyhhdhyysyyssssoo+oo+++++////+++oo+++++oo++/+++//:`             ",
	"             `-:///++oooooss++ooosyhhyhhhhhyyyssssoo++/+++++oo++++ooo+++oo++++++++++:.            ",
	"           .:////oooososyo+soooossssyyyhhhhyyyysss++++/+ooo++so+o+o+oooo+ooo+++++++/++.           ",
	"          -+++oooosy+:--+o+/+ooooossyyyyyyyyyssso+++ososooososo++++oooo++++++/++/+++oo/.          ",
	"         .++ooooosyo.```/++/ooo+sssysyyyyssssss+o+oooosooo+o+oo+++oooooooo++ooo+++++++++.         ",
	"        `/+ooosssyyo/::+sos+ossoosssossssssoooooo+oooooooo+++++oo+oooooooo+ooo++o+//+++//`        ",
	"       `/+++oosssyyyssssoso/ossssyso++ooos+/+ooosoo++ooo+/++oo+soo+ooooooo+oooooo++++++//:        ",
	"      `/+oooosssyyysssooooo+ossssso++ooooooooooo+ooo+++++///+ooo++++ooo+ooooo+o++oooooo+//        ",
	"      :osssssoososooooso+o+oooooss//+oososoooo+o+++/+++//+//++++ooooooooooo+ooo+oooooooo+/.       ",
	"      /ososso+ooooosooo+//+++ooss+/+o++++o+oooooo+/::////////+++oooooooooo+ooooooooooooo+//       ",
	"     `+/++oo///+o+oooo++///+osyy+//+++++++//++ooo+//::/::///++++++++oo+++oooooooooo+ooo+++/`      ",
	"      .:/+o++//+/++o+oo//+ossso/:++++o++ooo//++o+/////::://///+++++oooooossossssossooo++++/:      ",
	"        -+s+++++++oooo++ossso/:/+/+++o+oooooo+o++++/////::/:/+o++oooooososssssssossossoo++//      ",
	"         `-.++oossssssooso+////++/+o++++oooooooo++///:://///+osooooooosossosssssoossoo+o++//-     ",
	"            `://++ooo+//////+++++++++o++oooooooo//:///////+ossssooo+oooossssssoososooooo++//:     ",
	"             `-:////++////++/+/+++/++ooooooo+++/:///////+oossyysooooosssoosssossooooo++o+++::`    ",
	"                `.::/++//+/+++++/++++ooooo+++++///////++o+osyyyssoooooooosssssssooooooo+++/:.     ",
	"                    .:///++++ooo+ooossso+++++++//+++++oo++ossysssoooooooooooooooosooooo++/::`     ",
	"                       .-/+ooooo+oosssssosoo+++++o+ooo+++ossyysssoooooo++o+oooooosooo+++/::`      ",
	"                         `.:++oooosssssssso+++oooooo++++osssysssssooooooooosoooooo++++/::-.       ",
	"                            `//+oosssssssso+++oooooooosossssssyyysss++////+++++++++++/:--`        ",
	"                           ./++//::++++++++++++//+/syssossoosossssss/:///+/+++/+++////::`         ",
	"                        `:/+ooo+/:++++//://+++////ooosssssooooo++/+++//://++//++++++//:`          ",
	"                       ./+o+++///++osoo++oooo+/:+oosoo++oooooooo////::://///////////:.`           ",
	"                      `//+/++///:+/-://+/oo++////o+:..-:/:/+:+/:/+//::::::::/:/+/--.              ",
	"                         `````-:-.` `..--..``   `.`. `    .` `.``..``` `.`` ````                  ",
	"                                                                                                  ",
}

local basil_3 = {
	"                                                                                   ",
	"                                                                                   ",
	"                                                   :o++/:.`                        ",
	"                                                   -/hhhhho+.                      ",
	"                                                   :hddhyyhhs:                     ",
	"                                                   -hhdhhhyyhh/`                   ",
	"                                                    :yhhhhsshyhs.                  ",
	"                          ./+//:-.``                `/hhdmyhydddy`                 ",
	"                  ``..-:://yhddddyo+:`               :yhddyysyydd/                 ",
	"              `-+ossssyyhdosdmmmmmmdhs/.             /hhdmddsyydsy                 ",
	"           `-+syyysyhhhdhhsohmmdmmmmmmdy:.           ohddmdddhddhh`                ",
	"         `/syhhyoyhhhhhddhsyhmmdhhdmmmmmds+.         +hdddddmmdddh`                ",
	"       ./oyhyhhhhddhdhhhdhyohdmmmmhhmmmmmmdh/```     .hdddddmdydmy                 ",
	"     `:shhhhyhhdddddhdhhhhhoydmmmmmdhmmmmmdyys+/--    /hddmdhdsodo                 ",
	"    :ohhhhdhyhhdddddhhhhhhyyohdmmmmmddmmmmmmhsyyso/-`  +dmmdddhds/                 ",
	"   :hdhhhdddhhhdddyyhddhdhyhoyhmmmmmmddmmmmmmdyhyyoso` `omddddyhh:                 ",
	"  .yhhdhhddmdhhddhhhhdddddyys+ydmmmmmdymmmmmmmmhssy+os:``hdhddhsh:                 ",
	" .ohyddyydhdhdhdyhdddddddddyossydmmmdddydmmmmmmmdoso+/s/-smyyddhd-                 ",
	" /hhyhhyddhhydhdydhddddhddhyyssssyyhhyhyyhdmdmmmmosoo++ooomydddmh.                 ",
	" /hysyhysdhhyhhdhddhhhddddhhyyddhsysoyyhhyhysyydmysoho+/o+dhddddho                 ",
	" -hdddssydhdhhdhdddhddhhddydhdddhsysososhyhdhhyyyhoshhhyshhdddmdhy/                ",
	" shdyydsyshddhhdhddddmdhyhdddhdddhdhhyyooo+hddsyyyyyhhhmshhhhdhhdhd+.              ",
	" +ddhssydsydddhdddddddddddmmddhddddddhysoooosyhhhdhhhhhdydhhdh+yyshmd+`            ",
	" :dhdhyshshyyhdhddddddddddmmdddddddddyyyosysooossyddhhdoydhhdddhhooshhy-           ",
	" .hdhdhdssssddddhddddddmdmmmmdddddysyyysyddysossy/shdddoddydddddmdhyhdhhy+.        ",
	" .shhhhhhshyyysshhdddddmdddmmdddddysydyhhdhdhhhhyooyddhhdddddddmdmmmddyyydh+       ",
	" `shdhddhshhddddssyhhdddmmmddhhhddddsyddhhhhdhyyyyyoyhdhhdyyyyhdmmmmdmhsdhhh+`     ",
	"  sdhhhhhsyyhddddhhhssdhhddddyyhhdddddddddhhhhysyhhhshdhhh+.:.-smNNmmmmddmdhy.     ",
	"  :shhhssyssoyddddhhohddddyhhddhhdddddddddddhs+hhyyhhdddhsy-.``:hmNNmmmmymhhy+:    ",
	" ``syhdhsosysshddyshddddhddhhhddddddhhhddddys+ohhhyyyhhhhhhyo+++dmNmNmmmmmdhyso.   ",
	"  .yhhhddhysoyshhhdhddhhyyyyyhhhhsdddddhhhdysoshhyyoyyhhhdhdhdddddddmmmmmddhhh+/   ",
	"  -yhddhddhsssshhhhddhdhhhyhsysoyhdmdddddyhys+ohyhhosyyyhddddddddysshdmNmddhdy+/   ",
	"  -shysdddhsosssyyshdhhddhhhdhssydhdmmdddhhyssssyyhhysyyyyddddddddysshdhdmhddhy:   ",
	"  `:yhohddddyososyyysyhhhdhyhsyshhhdddddddhyhyoosyhhssyyyshhdddddmmhsshhdhdhhhho`` ",
	"    -//+yhhddhyssyyyyysyhhhsoyhoyyyyddddddddddssosshysshhhdhhhhdddddhhhddyhhhyhh:` ",
	"     `.:+ohhhhhyysyyyyyoyhhhyyoyssdyydhhhhhhhyoysososhyhhhddhhhhhyysoosddhysyyys-  ",
	"        `.oyhhhhhyyyyosssysoyyss+shhyshhhyhhdhyssosooossyyhhhhhyysso//osyysyys-`   ",
	"         `.++syhhhhyssyoooosossssoyhyyyhhyhdddyyysososoo++sosyyyyy+ssssyyyo/-`     ",
	"          `./o+syyhyyhhysysssooososysshhhhhydddhhyssosoooo++osyyyyyssso++:`        ",
	"            `-+yhhhhhhyyyysyyoss+/+oo/+ssyyhhydhhhhhhyyoooosssoo+syso-             ",
	"               `:+oyhsosyhhssy+/`  `  `.-+syyhyyhhhhhdhhyysyyyyssoooo/:`           ",
	"                  `.:ohyhhhh+s/-`         `-+ssyssssssssys++/ooos+ssoso.           ",
	"                     ``-//os:` ``           `/oyso+o+oooso+o//oosssyyss:`          ",
	"                         ``                    -sysyyyyoosoosos+oysyyh:``          ",
	"                                                 `/syhyssyyy+y+:```                ",
}

dashboard.section.header.val = basil_3

dashboard.section.buttons.val = {
	dashboard.button("e", "New", ":ene <BAR> startinsert <CR>"),
	dashboard.button("f", "Find", ":Telescope find_files<CR>"),
	dashboard.button("r", "Recent", ":Telescope oldfiles<CR>"),
	dashboard.button("q", "Quit", ":qa<CR>"),
}

alpha.setup(dashboard.opts)
